clc; clear all; close all;

fs = 44100;
data_folder = 'C:\Users\maria\OneDrive\Υπολογιστής\uni\Διπλωματικη\FINAL\Data';

%% Lookup 
hrtf = SOFAload('D2_44K_16bit_256tap_FIR_SOFA.sofa');
fprintf('Initializing lookup table\n');
tic;
lookup = itd2angle_lookuptable(hrtf, fs, 'dietz2011');
fprintf('Lookup table completed in %.1f sec\n', toc)

%% Load the metadata CSV generated by Python
meta = readtable('room_metadata.csv');

%% Preallocate new result columns
nRows = height(meta);
meta.Estimated_Az = nan(nRows,1);
meta.ITD_s        = nan(nRows,1);
meta.ILD_dB       = nan(nRows,1);
meta.Phi_std      = nan(nRows,1);

%% Main loop — process each file listed in the metadata table
for i = 1:nRows
    wav_file = fullfile(data_folder, meta.filename{i});
    try
        [insig, ~] = audioread(wav_file);
        fprintf('Processing: %s\n', meta.filename{i});
        if size(insig,1) < size(insig,2), insig = insig'; end

        [phi, phi_std, itd, ild, ~] = wierstorf2013_estimateazimuth( ...
            insig, lookup, 'fs', fs, 'dietz2011', 'remove_outlier');

        m_phi = median(phi(:), 'omitnan');       % phi is already in degrees
        m_itd = median(itd(:), 'omitnan');
        m_ild = median(ild(:), 'omitnan');
        m_std = mean(phi_std(:), 'omitnan');

        meta.Estimated_Az(i) = m_phi;
        meta.ITD_s(i)        = m_itd;
        meta.ILD_dB(i)       = m_ild;
        meta.Phi_std(i)      = m_std;

        fprintf('  Az=%g° -> Estimated: %.1f° (RT60_merged=%.3fs, std=%.1f)\n', ...
            meta.azimuth(i), m_phi, meta.rt60_merged(i), m_std);

        if mod(i, 20) == 0
        fprintf('--- Progress: %d/%d files processed ---\n', i, nRows);
        end
        
    catch ME
        fprintf('  Error: %s\n', ME.message);
    end
end

%% Save combined results
writetable(meta, fullfile(data_folder, 'results_with_rt60.csv'));
fprintf('Saved combined results to results_with_rt60.csv\n');


